refactor/process log bb
paygoc6/action-openapi-linter pull request #9
Opened 2020-12-14 15:13 UTC by ianffcs

- refactoring on script
- better xf
- better xf

2020-12-14 15:18 UTC, beatrizanami-paygo commented on process-log.bb
> +#_(->> *command-line-args*
Remover comentário

2020-12-14 15:21 UTC, fernandocarvalhopaygo commented on process-log.bb
> +;; make test for this
Comentário

2020-12-14 15:21 UTC, fernandocarvalhopaygo approved these changes

2020-12-14 15:24 UTC, beatrizanami-paygo requested changes

2020-12-14 15:24 UTC, beatrizanami-paygo commented on process-log.bb
> +(let [xf (comp
Acho bom colocar uma variável com um nome mais claro

2020-12-14 15:24 UTC, beatrizanami-paygo commented on process-log.bb
> +;; make test for this
Remover comentário e adicionar o teste

2020-12-14 15:24 UTC, beatrizanami-paygo commented on process-log.bb
> +;; make test for this
Talvez criar uma task pra criar um workflow de validação

2020-12-14 17:31 UTC, brmrodrigues commented on process-log.bb
> +       (mapcat log->treated-plog)
why plog?

2020-12-14 20:20 UTC, marciol commented on process-log.bb
> +(let [xf (comp
Estou achando que esse `xf` ai tem haver com transducer, ou estou errado @ianffcs?

2020-12-15 19:02 UTC, ianffcs commented on process-log.bb
> +(let [xf (comp
é um transducer  sim

2020-12-15 19:02 UTC, ianffcs commented on process-log.bb
> +       (mapcat log->treated-plog)
processed-log

2020-12-15 20:39 UTC, brmrodrigues approved these changes

2020-12-15 22:06 UTC, merged